### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fniekiel** [ercius/openNCEM#1]
Need to figure out, which license we put this under!

**Comment by ercius** [comment]
Yes definitely. Anyone have a preference or experience with this?

**Comment by tcpekin** [comment]
I've seen a lot of projects use one of the GPL licenses. After looking into it a bit, it seems like it's about as open as one can get. Derivatives, even ones that are commercialized, have to be published under the same license and completely open (copyleft is the term apparently). This is also what hyperspy uses (GPL v.3).

**Comment by fniekiel** [comment]
GNU LGPLv3

**Comment by fniekiel** [comment]
Sorry for bringing this up once more.

Turned out that the PySide issue inhibits me from using the GUI tools on any other machine, than that funny broken ubuntu one where you can have the unsupported case of PySide running with python3.5.

The easiest way would be to migrate over to PyQt4, which I just tested. Almost no code changes, BUT it would imply that we have to move to the GPLv3 instead of the LGPLv3 license.

Would this be ok with you?

**Comment by tcpekin** [comment]
Yes from me.

**Comment by ercius** [comment]
Yes from me

**Comment by fniekiel** [comment]
After talking to Colin, GPLv3 it is.
