### ISSUE TITLE
SER array size backwards

### ISSUE THREAD

**Issue by ercius** [ercius/openNCEM#10]
The ser reader code does not work for non-square images. I think that the values in reshape() in line 380 in getDataset() need to be swapped.

**Comment by fniekiel** [comment]
That's quite possible, I never had the chance to try non-square images ...
Can you take care of it?

**Comment by ercius** [comment]
Yes. Will do!

**Comment by ercius** [comment]
Ok. I changed the ser.py file to use the reverse ArraySize. I left everything else the same though. We may need to change everything with respect to the dimensions (pixel size, reported array size, dim vectors in writeEMD, etc.)
