### ISSUE TITLE
Submodule name io clobbers built in python3 module io

### ISSUE THREAD

**Issue by ZGainsforth** [ercius/openNCEM#14]
The standard library in python 3 for dealing with file streams is called io.  Having our own submodule named io can clobber that namespace and cause incompatibilities with other code using io.

It also can cause a "bizzare" error in my zsh shell where it reports "Fatal Python error: Py_Initialize: can't initialize sys standard streams" because the python system standard streams depends on the builtin io.

I don't know but I suspect this could also be related to https://github.com/ercius/openNCEM/issues/12

A simple solution is to choose a name for io which is different than the builtin io module.  I suggest ncemio.

**Comment by ercius** [comment]
@ZGainsforth Thanks for commenting on this. I have started using `import ncempy.io as nio` which gives the module a unique name and its easy to type. If this is still causing issues for other people we can consider renaming the module if needed.
