### ISSUE TITLE
Need a place to put images and binary files

### ISSUE THREAD

**Issue by fniekiel** [ercius/openNCEM#2]
We need some space to upload images for the documentation and the possibility to provide the example datasets which I have been using for unittesting. Without them, the unittests fail.

For the images I will attach them to this issue for now, to have them immediately available.

**Comment by fniekiel** [comment]
![gui_ser2emd](https://cloud.githubusercontent.com/assets/23124266/20652214/d09b7f1e-b4a9-11e6-854c-3ebc27202001.png)

**Comment by fniekiel** [comment]
![gui_ringdiff_lmax1](https://cloud.githubusercontent.com/assets/23124266/20652218/dbff2964-b4a9-11e6-9985-b7e6594e2924.png)
![gui_ringdiff_polar](https://cloud.githubusercontent.com/assets/23124266/20652219/de507d12-b4a9-11e6-8713-91211197aea9.png)
![gui_ringdiff_radprof](https://cloud.githubusercontent.com/assets/23124266/20652220/e02cd0c2-b4a9-11e6-9077-7d637fc2e19d.png)

**Comment by ercius** [comment]
Will start putting data and test data in ncempy/data. Will significantly reduce the size of the test data so that it can be easily distributed with the code.
