### ISSUE TITLE
Example code

### ISSUE THREAD

**Issue by ercius** [ercius/openNCEM#7]
I suggest we update the docs in ncempy/io to include a quick start example(s) "how to read a dataset using SER.py, EMD.py, etc. "

**Comment by fniekiel** [comment]
I totally agree. In fact you are pointing on a bigger issue which is the documentation I did not find the time to write yet:

- getting started with ncempy (how to install)
- how to install and use the tools
  - documentation for RingDiff user interface
  - documentation for ser2emd user interface
- how to use the algorithms from python (like manually do RingDiff evaluation)
- the usage of the file format classes, you have mentioned

We probably should start putting up a structure on where these things go and than fill them in one after the other.

**Comment by ercius** [comment]
Yes. Those all sound like excellent ideas. Im not familiar with readthedocs, but it should be fairly simple to get started with that. Do you have any suggestions for the structure we should use?
